/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Activos.View;

import Activos.Aplicacion.Aplicacion;
import Activos.Controller.ActivosController;
import Activos.Entidades.Activos;
import Activos.Model.ActivosModel;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jas Pal
 */
public class ActivosView extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form ActivosView
     */
    public ActivosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codeLabel = new javax.swing.JLabel();
        activeLabel = new javax.swing.JLabel();
        fabricacionLabel = new javax.swing.JLabel();
        valorOriginalLabel = new javax.swing.JLabel();
        categoriLabel = new javax.swing.JLabel();
        codeTxtField = new javax.swing.JTextField();
        activeTxtField = new javax.swing.JTextField();
        fabricationTxtField = new javax.swing.JTextField();
        originalValueTxtLabel = new javax.swing.JTextField();
        ComboCategorias = new javax.swing.JComboBox();
        ageLabel = new javax.swing.JLabel();
        depreciationLabel = new javax.swing.JLabel();
        currentValueLabel = new javax.swing.JLabel();
        ageTxtField = new javax.swing.JTextField();
        depreciationTxtField = new javax.swing.JTextField();
        currentValueTxtFiedl = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButtom = new javax.swing.JButton();
        consultButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codeLabel.setText("Codigo");

        activeLabel.setText("Activo");

        fabricacionLabel.setText("Fabricacion");

        valorOriginalLabel.setText("Valor Original");

        categoriLabel.setText("Categoria");

        ageLabel.setText("Edad");

        depreciationLabel.setText("Deprecicaion");

        currentValueLabel.setText("Valor Actual");

        ageTxtField.setEditable(false);

        depreciationTxtField.setEditable(false);

        currentValueTxtFiedl.setEditable(false);

        addButton.setText("Agregar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButtom.setText("Modificar");
        updateButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtomActionPerformed(evt);
            }
        });

        consultButtom.setText("Consultar");
        consultButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consultButtom)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeLabel)
                            .addComponent(activeLabel)
                            .addComponent(fabricacionLabel)
                            .addComponent(valorOriginalLabel)
                            .addComponent(categoriLabel))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(originalValueTxtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(codeTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(activeTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fabricationTxtField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ageLabel)
                                        .addGap(55, 55, 55)
                                        .addComponent(ageTxtField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(depreciationLabel)
                                            .addComponent(currentValueLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(currentValueTxtFiedl)
                                            .addComponent(depreciationTxtField)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(updateButtom)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel)
                    .addComponent(codeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel)
                    .addComponent(ageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activeLabel)
                    .addComponent(activeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depreciationLabel)
                    .addComponent(depreciationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fabricacionLabel)
                    .addComponent(fabricationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentValueLabel)
                    .addComponent(currentValueTxtFiedl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorOriginalLabel)
                    .addComponent(originalValueTxtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriLabel)
                    .addComponent(ComboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(consultButtom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(updateButtom))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        controller.agregar();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtomActionPerformed
        controller.modificar();
    }//GEN-LAST:event_updateButtomActionPerformed

    private void consultButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultButtomActionPerformed
        try {
            controller.buscar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Activo no Existe", "", JOptionPane.ERROR_MESSAGE);
            controller.clearPantalla();
        }
    }//GEN-LAST:event_consultButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox ComboCategorias;
    private javax.swing.JLabel activeLabel;
    public javax.swing.JTextField activeTxtField;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel ageLabel;
    public javax.swing.JTextField ageTxtField;
    private javax.swing.JLabel categoriLabel;
    private javax.swing.JLabel codeLabel;
    public javax.swing.JTextField codeTxtField;
    private javax.swing.JButton consultButtom;
    private javax.swing.JLabel currentValueLabel;
    public javax.swing.JTextField currentValueTxtFiedl;
    private javax.swing.JLabel depreciationLabel;
    public javax.swing.JTextField depreciationTxtField;
    private javax.swing.JLabel fabricacionLabel;
    public javax.swing.JTextField fabricationTxtField;
    public javax.swing.JTextField originalValueTxtLabel;
    private javax.swing.JButton updateButtom;
    private javax.swing.JLabel valorOriginalLabel;
    // End of variables declaration//GEN-END:variables

    ActivosController controller;
    ActivosModel model;

    public void setController(ActivosController controller) {
        this.controller = controller;
    }

    public void setModel(ActivosModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public ActivosModel getModel() {
        return model;
    }

    @Override
    public void update(Observable o, Object o1) {
        Activos current = model.getCurrent();

        codeTxtField.setText(current.getCodigo());
        if (model.getErrores().get("codigo") != null) {
            codeTxtField.setBorder(Aplicacion.BORDER_ERROR);
            codeTxtField.setToolTipText(model.getErrores().get("codigo"));
        } else {
            codeTxtField.setBorder(null);
            codeTxtField.setToolTipText("");
        }

        activeTxtField.setText(current.getNombre());
        if (model.getErrores().get("activo") != null) {
            activeTxtField.setBorder(Aplicacion.BORDER_ERROR);
            activeTxtField.setToolTipText(model.getErrores().get("activo"));
        } else {
            activeTxtField.setBorder(null);
            activeTxtField.setToolTipText("");
        }

        fabricationTxtField.setText(String.valueOf(current.getFabricacion()));
        if (model.getErrores().get("fabricacion") != null) {
            fabricationTxtField.setBorder(Aplicacion.BORDER_ERROR);
            fabricationTxtField.setToolTipText(model.getErrores().get("fabricacion"));
        } else {
            fabricationTxtField.setBorder(null);
            fabricationTxtField.setToolTipText("");
        }

        originalValueTxtLabel.setText(String.valueOf(current.getValor()));
        if (model.getErrores().get("valor original") != null) {
            codeTxtField.setBorder(Aplicacion.BORDER_ERROR);
            codeTxtField.setToolTipText(model.getErrores().get("valor original"));
        } else {
            codeTxtField.setBorder(null);
            codeTxtField.setToolTipText("");
        }

        ComboCategorias.setModel(model.getCategorias());
        ComboCategorias.setSelectedItem(current.getCategoria());
        if (codeTxtField.getText().length()!=0) {
            ageTxtField.setText(String.valueOf(model.Edad()));
            depreciationTxtField.setText(String.valueOf(model.Depreciacion()));
            valorOriginalLabel.setText(String.valueOf(model.ValorActual()));
        } 

        this.validate();
        if (!model.getMensaje().equals("")) {
            JOptionPane.showMessageDialog(this, model.getMensaje(), "", JOptionPane.INFORMATION_MESSAGE);
        }
    }

}
